name: Build LaTeX CV
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: apt-get install -y texlive-base texlive-fonts-extra texlive-pictures texlive-latex-extra texlive-latex-recommended
      - env:
          MAILTO: ${{ secrets.MAILTO }}
          FULLNAME: ${{ secrets.FULLNAME }}
          LINKEDIN: ${{ secrets.LINKEDIN }}
        run: make

      - name: Move .pdf to public/
        env:
          FILENAME_ENGLISH: ${{ secrets.FILENAME_ENGLISH }}
          FILENAME_SPANISH: ${{ secrets.FILENAME_SPANISH }}
        run: |
          sed -i 's/FILENAME_ENGLISH/'"${FILENAME_ENGLISH}"'/' public/index.html
          sed -i 's/FILENAME_SPANISH/'"${FILENAME_SPANISH}"'/' public/index.html
          cp -v CV.pdf    public/${FILENAME_ENGLISH}
          cp -v CV_es.pdf public/${FILENAME_SPANISH}

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
