name: Build LaTeX CV

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repository
        uses: actions/checkout@v2
      - name: Build Resume
        uses: xu-cheng/latex-action@v2
        with:
          pre_compile: "tlmgr update --self && tlmgr update --all && tlmgr install geometry hyperref titlesec titling fontawesome lastpage fancyhdr"
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode
          root_file: CV.tex
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: CV.pdf
