name: Build LaTeX CV
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/latex-action@v3
        env:
          MAILTO: ${{ secrets.MAILTO }}
          FULLNAME: ${{ secrets.FULLNAME }}
          LINKEDIN: ${{ secrets.LINKEDIN }}
        with:
          pre_compile: "tlmgr install geometry hyperref titlesec titling fontawesome lastpage fancyhdr randtext multirow makecell babel-spanish"
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode
          root_file: |
            CV.tex
            CV_es.tex

      - name: Move .pdf to public/
        env:
          FILENAME_ENGLISH: ${{ secrets.FILENAME_ENGLISH }}
          FILENAME_SPANISH: ${{ secrets.FILENAME_SPANISH }}
        run: |
          sed -i 's/FILENAME_ENGLISH/'"${FILENAME_ENGLISH}"'/' public/index.html
          sed -i 's/FILENAME_SPANISH/'"${FILENAME_SPANISH}"'/' public/index.html
          cp -v CV.pdf    public/${FILENAME_ENGLISH}
          cp -v CV_es.pdf public/${FILENAME_SPANISH}

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
