name: Build LaTeX CV

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repository
        uses: actions/checkout@v2
      - name: Build Resume
        uses: xu-cheng/latex-action@v2
        with:
          root_file: CV.tex
