name: Build LaTeX CV
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/latex-action@v2
        env:
          MAILTO: ${{ secrets.MAILTO }}
          FULLNAME: ${{ secrets.FULLNAME }}
          LINKEDIN: ${{ secrets.LINKEDIN }}
        with:
          pre_compile: "tlmgr update --self && tlmgr update --all && tlmgr install geometry hyperref titlesec titling fontawesome lastpage fancyhdr randtext multirow makecell"
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode
          root_file: CV.tex

      - name: Move .pdf to public/
        env:
          FILENAME: ${{ secrets.FILENAME }}
        run: |
          mkdir -p public/
          cp -v CV.pdf public/$FILENAME

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
